const API = 'https://www.googleapis.com/blogger/v3';
const AUTH = 'https://accounts.google.com/o/oauth2/v2/auth';
const TOKEN = 'https://oauth2.googleapis.com/token';
const USERINFO = 'https://openidconnect.googleapis.com/v1/userinfo';
const BLOGGER = 'https://www.googleapis.com/auth/blogger';
const SCOPES = [BLOGGER, 'openid', 'email', 'profile'];
const SESSION_TTL = 604800;
const STATE_TTL = 600;

export default { async fetch(req, env) {
  const url = new URL(req.url);
  try {
    if (req.method === 'OPTIONS') return cors(new Response(null, {status:204}), env);
    if (url.pathname === '/api/health') return cors(json({ok:true, service:'extension-blogger-publisher'}), env);
    if (url.pathname === '/api/auth/login' && req.method === 'POST') return cors(await login(req, env), env);
    if (url.pathname === '/api/auth/logout' && req.method === 'POST') return cors(await logout(req, env), env);
    if (url.pathname === '/api/auth/me') return cors(await auth(req, env, true), env);
    if (url.pathname === '/oauth/google/start') return await oauthStart(req, env);
    if (url.pathname === '/oauth/google/callback') return await oauthCallback(req, env);
    const session = await auth(req, env);
    if (session instanceof Response) return cors(session, env);
    if (url.pathname === '/api/accounts' && req.method === 'GET') return cors(await accounts(env), env);
    if (url.pathname.startsWith('/api/accounts/') && url.pathname.endsWith('/disconnect') && req.method === 'POST') return cors(await disconnect(decodeURIComponent(url.pathname.split('/')[3]), env), env);
    if (url.pathname === '/api/accounts/refresh' && req.method === 'POST') return cors(await refreshAccounts(env), env);
    if (url.pathname === '/api/publish' && req.method === 'POST') return cors(await publish(req, env, session), env);
    if (url.pathname === '/api/publications/recent') return cors(await recent(env), env);
    return cors(json({error:'Not found'},404), env);
  } catch (e) { console.error('request_error', {path:url.pathname, message:e?.message}); return cors(json({error:'Internal server error'},500),env); }
}};

async function login(req,env){
  need(env,'CMS_ADMIN_PASSWORD','SESSION_SECRET'); const b=await body(req);
  if(!b?.password || !timingSafe(b.password,env.CMS_ADMIN_PASSWORD)) return json({error:'Invalid administrator credentials'},401);
  const id=randomId(32); await env.APP_KV.put(`session:${id}`,JSON.stringify({cmsUserId:'bootstrap-admin'}),{expirationTtl:SESSION_TTL});
  return cookie(json({ok:true,user:{id:'bootstrap-admin',role:'admin'}}),'publisher_session',id,SESSION_TTL);
}
async function logout(req,env){const id=cookies(req).publisher_session;if(id)await env.APP_KV.delete(`session:${id}`);return clearCookie(json({ok:true}),'publisher_session');}
async function auth(req,env,asResponse=false){const id=cookies(req).publisher_session;const s=id?await env.APP_KV.get(`session:${id}`,'json'):null;if(!s)return asResponse?json({authenticated:false},401):json({error:'Authentication required'},401);return asResponse?json({authenticated:true,user:{id:s.cmsUserId,role:'admin'}}):s;}

async function oauthStart(req,env){const s=await auth(req,env);if(s instanceof Response)return s;need(env,'GOOGLE_CLIENT_ID','GOOGLE_REDIRECT_URI');const state=randomId(32);await env.APP_KV.put(`oauth_state:${state}`,JSON.stringify({sessionId:cookies(req).publisher_session}),{expirationTtl:STATE_TTL});const p=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:env.GOOGLE_REDIRECT_URI,response_type:'code',access_type:'offline',prompt:'consent',include_granted_scopes:'true',scope:SCOPES.join(' '),state});return Response.redirect(`${AUTH}?${p}`,302);}

async function oauthCallback(req,env){need(env,'GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_REDIRECT_URI','TOKEN_ENCRYPTION_KEY');const u=new URL(req.url),state=u.searchParams.get('state'),code=u.searchParams.get('code');if(!state||!code)return appRedirect(env,'oauth_error=missing_code');const st=await env.APP_KV.get(`oauth_state:${state}`,'json');await env.APP_KV.delete(`oauth_state:${state}`);if(!st)return appRedirect(env,'oauth_error=invalid_state');if(!(await env.APP_KV.get(`session:${st.sessionId}`,'json')))return appRedirect(env,'oauth_error=session_expired');
  const tr=await fetch(TOKEN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:env.GOOGLE_REDIRECT_URI,grant_type:'authorization_code'})});const t=await tr.json().catch(()=>({}));if(!tr.ok||!t.access_token){console.error('oauth_exchange',{status:tr.status,error:t.error});return appRedirect(env,'oauth_error=token_exchange_failed');}
  const profile=await google(USERINFO,t.access_token);if(!profile?.sub)return appRedirect(env,'oauth_error=profile_failed');const id=`google:${profile.sub}`,old=await env.APP_KV.get(`account:${id}`,'json');if(!t.refresh_token&&!old?.encryptedRefreshToken)return appRedirect(env,'oauth_error=missing_refresh_token');const account={id,provider:'google',googleSub:profile.sub,email:profile.email||null,name:profile.name||null,encryptedRefreshToken:t.refresh_token?await encrypt(t.refresh_token,env.TOKEN_ENCRYPTION_KEY):old.encryptedRefreshToken,encryptedAccessToken:await encrypt(t.access_token,env.TOKEN_ENCRYPTION_KEY),accessTokenExpiresAt:Date.now()+Number(t.expires_in||3600)*1000,status:'connected',lastAuthorizedAt:new Date().toISOString(),lastError:null,blogs:old?.blogs||[]};await env.APP_KV.put(`account:${id}`,JSON.stringify(account));await addIndex(env,id);try{account.blogs=await listBlogs(account,env);await env.APP_KV.put(`account:${id}`,JSON.stringify(account));}catch(e){account.status=e.code==='AUTH_REQUIRED'?'reauthorization_required':'error';account.lastError=safe(e);await env.APP_KV.put(`account:${id}`,JSON.stringify(account));}return appRedirect(env,'connected=1');}

async function accounts(env){const ids=await index(env),items=(await Promise.all(ids.map(id=>env.APP_KV.get(`account:${id}`,'json')))).filter(Boolean);return json({accounts:items.map(publicAccount)});}
async function disconnect(id,env){if(!await env.APP_KV.get(`account:${id}`,'json'))return json({error:'Account not found'},404);await env.APP_KV.delete(`account:${id}`);await env.APP_KV.put('accounts:index',JSON.stringify((await index(env)).filter(x=>x!==id)));return json({ok:true});}
async function refreshAccounts(env){const out=[];for(const id of await index(env)){const a=await env.APP_KV.get(`account:${id}`,'json');if(!a)continue;try{await token(a,env,true);out.push({id,status:'connected'});}catch(e){out.push({id,status:e.code==='AUTH_REQUIRED'?'reauthorization_required':'error',error:safe(e)});}}return json({results:out});}

async function publish(req,env,session){need(env,'GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','TOKEN_ENCRYPTION_KEY');const p=await body(req),err=validate(p);if(err)return json({error:err},400);const all=(await Promise.all((await index(env)).map(id=>env.APP_KV.get(`account:${id}`,'json')))).filter(Boolean),map=new Map();for(const a of all)for(const b of a.blogs||[])map.set(String(b.id),{account:a,blog:b});const operationId=randomId(16);const results=await Promise.all([...new Set(p.blogIds.map(String))].map(id=>{const x=map.get(id);return x?publishOne(x.account,x.blog,p,operationId,session.cmsUserId,env):result(id,null,false,'Blog is not connected or access is no longer available');}));return json({operationId,results});}

async function publishOne(account,blog,p,operationId,cmsUserId,env){const key=pubKey(blog.id,p.slug,p.chapterNumber),old=await env.APP_KV.get(key,'json');if(old?.status==='success'||old?.status==='duplicate')return result(blog.id,blog,false,'Duplicate prevented',old.url,'duplicate');const fingerprint=await sha256(`${blog.id}|${p.slug}|${p.chapterNumber||''}`),label=`ext-${fingerprint.slice(0,48)}`,marker=`<!-- extension-publisher:${fingerprint} -->`,content=buildContent(p,marker);const base={operationId,cmsUserId,blogId:String(blog.id),blogName:blog.name,accountId:account.id,accountEmail:account.email,slug:p.slug,chapterNumber:p.chapterNumber||null,createdAt:new Date().toISOString()};try{let access=await token(account,env);let duplicate=await findDuplicate(blog.id,label,access);if(duplicate)return await markDuplicate(key,base,duplicate,blog);const payload={title:p.title,content,labels:[...(p.labels||[]),label]};let r;try{r=await blogger(`/blogs/${encodeURIComponent(blog.id)}/posts?isDraft=false`,access,{method:'POST',body:JSON.stringify(payload)});}catch(e){if(e.httpStatus!==401)throw e;access=await token(await env.APP_KV.get(`account:${account.id}`,'json'),env,true);duplicate=await findDuplicate(blog.id,label,access);if(duplicate)return await markDuplicate(key,base,duplicate,blog);r=await blogger(`/blogs/${encodeURIComponent(blog.id)}/posts?isDraft=false`,access,{method:'POST',body:JSON.stringify(payload)});}await env.APP_KV.put(key,JSON.stringify({...base,status:'success',postId:r.id||null,url:r.url||null,finishedAt:new Date().toISOString()}));return result(blog.id,blog,true,null,r.url,'success');}catch(e){const status=e.code==='AUTH_REQUIRED'?'reauthorization_required':'failed';await env.APP_KV.put(key,JSON.stringify({...base,status,error:safe(e),finishedAt:new Date().toISOString()}));return result(blog.id,blog,false,friendly(e),null,status);}}
async function markDuplicate(key,base,duplicate,blog){await env.APP_KV.put(key,JSON.stringify({...base,status:'duplicate',postId:duplicate.id||null,url:duplicate.url||null,finishedAt:new Date().toISOString()}));return result(blog.id,blog,false,'Already published',duplicate.url,'duplicate');}

async function findDuplicate(blogId,label,access){try{const d=await blogger(`/blogs/${encodeURIComponent(blogId)}/posts?labels=${encodeURIComponent(label)}&maxResults=10&fetchBodies=false`,access);return d.items?.[0]||null;}catch(e){if(e.httpStatus===403||e.httpStatus===404)return null;throw e;}}
async function listBlogs(account,env){const a=await token(account,env);const d=await blogger('/users/self/blogs?fields=items(id,name,url,published,updated)',a);return(d.items||[]).map(b=>({id:String(b.id),name:b.name||String(b.id),url:b.url||null,published:b.published||null,updated:b.updated||null}));}

async function token(account,env,force=false){if(!force&&account.encryptedAccessToken&&Number(account.accessTokenExpiresAt||0)>Date.now()+60000)return decrypt(account.encryptedAccessToken,env.TOKEN_ENCRYPTION_KEY);if(!account.encryptedRefreshToken)throw authError('Reconnect this Google account to restore Blogger access');const rt=await decrypt(account.encryptedRefreshToken,env.TOKEN_ENCRYPTION_KEY);const r=await fetch(TOKEN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,refresh_token:rt,grant_type:'refresh_token'})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token){if(r.status===401||d.error==='invalid_grant'){account.status='reauthorization_required';account.lastError='Google authorization was revoked or expired';await env.APP_KV.put(`account:${account.id}`,JSON.stringify(account));throw authError('Google authorization expired or was revoked; reconnect this account');}throw apiError('Google token refresh failed',r.status);}account.encryptedAccessToken=await encrypt(d.access_token,env.TOKEN_ENCRYPTION_KEY);account.accessTokenExpiresAt=Date.now()+Number(d.expires_in||3600)*1000;account.status='connected';account.lastError=null;await env.APP_KV.put(`account:${account.id}`,JSON.stringify(account));return d.access_token;}

async function blogger(path,access,options={}){const headers={Authorization:`Bearer ${access}`,Accept:'application/json',...(options.body?{'content-type':'application/json'}:{})};const r=await fetch(`${API}${path}`,{...options,headers}),d=await r.json().catch(()=>({}));if(!r.ok)throw apiError(mapError(r.status,d),r.status);return d;}
async function google(url,access){const r=await fetch(url,{headers:{Authorization:`Bearer ${access}`,Accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Google profile request failed (${r.status})`);return d;}
async function recent(env){const keys=await env.APP_KV.list({prefix:'publication:'}),items=(await Promise.all(keys.keys.slice(0,100).map(k=>env.APP_KV.get(k.name,'json')))).filter(Boolean);items.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return json({publications:items.slice(0,50)});}

function buildContent(p,marker){let content=p.content.trim();if(p.featuredImage){try{const u=new URL(p.featuredImage);if(u.protocol==='http:'||u.protocol==='https:')content=`<p><img src="${escapeAttr(u.href)}" alt="${escapeAttr(p.title)}"></p>\n${content}`;}catch{}}return `${content}\n${marker}`;}
function validate(p){if(!p||typeof p.title!=='string'||!p.title.trim())return'Title is required';if(typeof p.slug!=='string'||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/i.test(p.slug.trim()))return'Slug must contain letters, numbers and hyphens only';if(typeof p.content!=='string'||!p.content.trim())return'Post content is required';if(!Array.isArray(p.blogIds)||!p.blogIds.length)return'Select at least one Blogger blog';if(p.blogIds.length>50)return'Too many blogs selected';return null;}
function result(id,blog,success,error=null,url=null,status=success?'success':'failed'){return{blogId:String(id),blogName:blog?.name||null,success,status,error,url};}
function pubKey(blog,slug,chapter){return`publication:${encodeURIComponent(String(blog)).slice(0,120)}:${encodeURIComponent(String(slug)).slice(0,120)}:${encodeURIComponent(String(chapter||'-')).slice(0,80)}`;}
function publicAccount(a){return{id:a.id,email:a.email,name:a.name,status:a.status,lastAuthorizedAt:a.lastAuthorizedAt,lastError:a.lastError,blogs:a.blogs||[]};}
function mapError(s,d){if(s===401)return'Blogger authorization expired';if(s===403)return'Insufficient Blogger permissions or Blogger API access is disabled';if(s===404)return'Blogger blog was not found or access was revoked';if(s===429)return'Blogger API rate limit reached; retry later';if(s>=500)return'Temporary Google/Blogger API failure';return d?.error?.message||`Blogger API request failed (${s})`;}
function friendly(e){if(e.code==='AUTH_REQUIRED')return e.message;if(e.httpStatus===429)return e.message;if(e.httpStatus>=500)return'Temporary Google API failure; retry this blog';return e.message||'Publishing failed';}
function authError(m){const e=new Error(m);e.code='AUTH_REQUIRED';return e;}function apiError(m,s){const e=new Error(m);e.httpStatus=s;return e;}
function need(env,...names){for(const n of names)if(!env[n])throw new Error(`Missing server configuration: ${n}`);}
async function index(env){return(await env.APP_KV.get('accounts:index','json'))||[];}async function addIndex(env,id){const x=await index(env);if(!x.includes(id))await env.APP_KV.put('accounts:index',JSON.stringify([...x,id]));}
async function body(req){try{return await req.json();}catch{return null;}}
function cookies(req){const out={};for(const x of(req.headers.get('Cookie')||'').split(';')){const i=x.indexOf('=');if(i>0)out[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim());}return out;}
function cookie(r,n,v,ttl){const h=new Headers(r.headers);h.append('Set-Cookie',`${n}=${v}; Max-Age=${ttl}; Path=/; HttpOnly; Secure; SameSite=Lax`);return new Response(r.body,{status:r.status,headers:h});}function clearCookie(r,n){const h=new Headers(r.headers);h.append('Set-Cookie',`${n}=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Lax`);return new Response(r.body,{status:r.status,headers:h});}
function json(d,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store'}});}function cors(r,env){const h=new Headers(r.headers),o=env.ALLOWED_ORIGIN||env.APP_BASE_URL||'';if(o)h.set('Access-Control-Allow-Origin',o);h.set('Access-Control-Allow-Credentials','true');h.set('Access-Control-Allow-Headers','Content-Type');h.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');return new Response(r.body,{status:r.status,headers:h});}
function appRedirect(env,q){return Response.redirect(`${env.APP_BASE_URL||'/'}?${q}`,302);}function randomId(n){const a=new Uint8Array(n);crypto.getRandomValues(a);return b64(a);}function b64(a){let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function fromB64(v){const p=v.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-v.length%4)%4),s=atob(p);return Uint8Array.from(s,c=>c.charCodeAt(0));}
async function sha256(v){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function key(secret){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret));return crypto.subtle.importKey('raw',h,'AES-GCM',false,['encrypt','decrypt']);}
async function encrypt(v,secret){const k=await key(secret),iv=crypto.getRandomValues(new Uint8Array(12)),c=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(v)),p=new Uint8Array(12+c.byteLength);p.set(iv);p.set(new Uint8Array(c),12);return b64(p);}
async function decrypt(v,secret){const p=fromB64(v),k=await key(secret),c=await crypto.subtle.decrypt({name:'AES-GCM',iv:p.slice(0,12)},k,p.slice(12));return new TextDecoder().decode(c);}
function timingSafe(a,b){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}function safe(e){return String(e?.message||'Unknown error').slice(0,500);}function escapeAttr(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
